## Tensorflow 기본

In [11]:
import tensorflow as tf

In [12]:
hello = tf.constant('Hello, Tensorflow!')
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [15]:
a = tf.constant(10)
b = tf.constant(32)
c=tf.add(a,b)
print(c)

Tensor("Add_1:0", shape=(), dtype=int32)


In [17]:
sess = tf.Session()

print(sess.run(hello))
print(sess.run([a,b,c]))

sess.close()

b'Hello, Tensorflow!'
[10, 32, 42]


In [27]:
X = tf.placeholder(tf.float32, [None,3])
print(X)

Tensor("Placeholder_2:0", shape=(?, 3), dtype=float32)


In [28]:
x_data = [[1,2,3],[4,5,6]]

In [29]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

In [30]:
expr = tf.matmul(X,W) + b

In [31]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print(" === b ===")
print(sess.run(b))
print("=== expr ===")
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[-0.26712593 -0.4395222 ]
 [-0.71958435 -0.14692414]
 [-0.21899548 -0.61731714]]
 === b ===
[[0.39365447]
 [1.3769264 ]]
=== expr ===
[[-1.9696268 -2.1916676]
 [-4.603472  -4.819686 ]]


`tf.global_variables_initializer()` : 앞에서 정의한 변수들을 초기화 하는 함수

In [32]:
x_data = [1,2,3]
y_data = [1,2,3]

W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")

hypothesis = W * X + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)

`with` 쓰면 세션 블록을 만들고 세션 종료를 자동으로 처리하도록 만듬

In [37]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(100):
        _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data, Y: y_data})
        
        print(step, cost_val, sess.run(W), sess.run(b))
    
    print("X: 5, Y:", sess.run(hypothesis, feed_dict={X: 5}))
    print("X: 2.5, Y:", sess.run(hypothesis, feed_dict={X: 2.5}))

0 5.8594127 [1.3352102] [-0.48403677]
1 0.10964945 [1.215962] [-0.5213135]
2 0.039083544 [1.2229228] [-0.5034356]
3 0.03644633 [1.2162358] [-0.4919176]
4 0.034705784 [1.2111827] [-0.4800284]
5 0.033057123 [1.2060902] [-0.46849582]
6 0.03148688 [1.2011377] [-0.45723274]
7 0.029991232 [1.1963023] [-0.44624126]
8 0.028566597 [1.1915834] [-0.4355139]
9 0.027209682 [1.1869779] [-0.42504448]
10 0.025917204 [1.182483] [-0.41482672]
11 0.024686133 [1.1780962] [-0.40485457]
12 0.023513496 [1.1738149] [-0.3951221]
13 0.022396611 [1.1696365] [-0.38562366]
14 0.021332748 [1.1655586] [-0.37635353]
15 0.020319423 [1.1615787] [-0.36730626]
16 0.019354235 [1.1576945] [-0.3584765]
17 0.018434921 [1.1539035] [-0.349859]
18 0.017559228 [1.1502038] [-0.3414486]
19 0.016725164 [1.146593] [-0.33324042]
20 0.015930675 [1.143069] [-0.32522953]
21 0.015173983 [1.1396297] [-0.31741124]
22 0.014453194 [1.1362731] [-0.3097809]
23 0.013766665 [1.1329973] [-0.30233398]
24 0.013112728 [1.1298001] [-0.2950661]
25 0.0

## 기본 신경망 구현

딥러닝은 다양한 분야에 사용되지만, 그 중 가장 폭 넓게 활용되는 분야는 패턴 인식을 통한 영상 처리<br  />
털과 날개가 있느냐를 기준으로 포유류와 조류를 구분하는 신경망 모델을 만들어 보겠다

In [38]:
import tensorflow as tf
import numpy as np

one-hot encoding: 데이ㅓㅌ가 가질 수 있는 값들을 일렬로 나열한 배열을 만들고,<br  />
그 중 표현하려는 값을 뜻하는 인덱스의 원소만 1로 표기하고<br  />
나머지 원소는 모두 0으로 채우는 표기법


In [39]:
x_data = np.array( [[0,0],[1,0],[1,1],[0,0],[0,0],[0,1]])
y_data = np.array([[1,0,0],[0,1,0],[0,0,1],[1,0,0],[1,0,0],[0,0,1]])

In [42]:
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [43]:
W = tf.Variable(tf.random_uniform([2,3], -1., 1.))
b = tf.Variable(tf.zeros([3]))

가중치 변수 `W`는 `[입력층(특징 수), 출력층(레이블 수)]`로 설정

In [44]:
L = tf.add(tf.matmul(X,W),b)
L = tf.nn.relu(L)

In [45]:
model = tf.nn.softmax(L)

신경망을 통해 나온 출력 값을 softmax 함수를 통해 사용하기 쉽게 다듬어준다.

In [47]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(model), axis=1))

원-핫 인코딩을 이용한 대부분의 모델에서 사용하는 cost function은 `교차 엔트로피 함수`<br  />
`cross-Entropy` : 예측값과 실제값 사이의 확률 분포 차이를 계산한 값

`reduce_XXX` 함수들은 텐서의 차원을 줄여준다.<br  />
함수 이름의 XXX 부분이 구체적인 차원 축소 방법을 뜻하고, axis 매개변수로 축소할 차원을 정한다<br  />
ex) `reduce_sum(<입력텐서>, axis=1)`은 주어진 텐서의 1번쨰 차원의 값들을 다 더해(1개로 만들어서)<br  />
그 차원을 없앤다는 뜻

In [48]:
#기초적인 경사하강법
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost)

# 텐서플로의 세션 초기화
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

# 학습 100번 진행
for step in range(100):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})

    if (step + 1) % 10 == 0:
        print(step + 1, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

10 1.2132281
20 1.2065412
30 1.2000782
40 1.1938308
50 1.1877905
60 1.1819496
70 1.1763002
80 1.1708347
90 1.165546
100 1.1604271


In [49]:
prediction = tf.argmax(model, axis=1)
target = tf.argmax(Y, axis=1)
print("예측값", sess.run(prediction, feed_dict={X: x_data}))
print('실제값:', sess.run(target, feed_dict={Y: y_data}))

예측값 [0 0 1 0 0 1]
실제값: [0 1 2 0 0 2]


`argmax 함수`: 예측 model을 바로 출력하면 확률로 나오기 때문에 요소 중 가장 큰 값의 인덱스를 찾아주는 함수

In [50]:
is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('정확도: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_data, Y: y_data}))

정확도: 50.00


### 심층 신경망 구현

In [56]:
# 털과 날개가 있는지 없는지에 따라, 포유류인지 조류인지 분류하는 신경망 모델을 만들어봅니다.
# 신경망의 레이어를 여러개로 구성하여 말로만 듣던 딥러닝을 구성해 봅시다!
import tensorflow as tf
import numpy as np

# [털, 날개]
x_data = np.array(
    [[0, 0], [1, 0], [1, 1], [0, 0], [0, 0], [0, 1]])

# [기타, 포유류, 조류]
y_data = np.array([
    [1, 0, 0],  # 기타
    [0, 1, 0],  # 포유류
    [0, 0, 1],  # 조류
    [1, 0, 0],
    [1, 0, 0],
    [0, 0, 1]
])

#########
# 신경망 모델 구성
######
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [57]:
# 첫번째 가중치의 차원은 [특성, 히든 레이어의 뉴런갯수] -> [2, 10] 으로 정합니다.
W1 = tf.Variable(tf.random_uniform([2, 10], -1., 1.))
# 두번째 가중치의 차원을 [첫번째 히든 레이어의 뉴런 갯수, 분류 갯수] -> [10, 3] 으로 정합니다.
W2 = tf.Variable(tf.random_uniform([10, 3], -1., 1.))

# 편향을 각각 각 레이어의 아웃풋 갯수로 설정합니다.
# b1 은 히든 레이어의 뉴런 갯수로, b2 는 최종 결과값 즉, 분류 갯수인 3으로 설정합니다.
b1 = tf.Variable(tf.zeros([10]))
b2 = tf.Variable(tf.zeros([3]))

In [58]:
# 신경망의 히든 레이어에 가중치 W1과 편향 b1을 적용합니다
L1 = tf.add(tf.matmul(X, W1), b1)
L1 = tf.nn.relu(L1)

In [59]:
# 최종적인 아웃풋을 계산합니다.
# 히든레이어에 두번째 가중치 W2와 편향 b2를 적용하여 3개의 출력값을 만들어냅니다.
model = tf.add(tf.matmul(L1, W2), b2)

# 텐서플로우에서 기본적으로 제공되는 크로스 엔트로피 함수를 이용해
# 복잡한 수식을 사용하지 않고도 최적화를 위한 비용 함수를 다음처럼 간단하게 적용할 수 있습니다.
cost = tf.reduce_mean(
    tf.nn.softmax_cross_entropy_with_logits(labels=Y, logits=model))

optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost)


#########
# 신경망 모델 학습
######
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for step in range(100):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})

    if (step + 1) % 10 == 0:
        print(step + 1, sess.run(cost, feed_dict={X: x_data, Y: y_data}))


#########
# 결과 확인
# 0: 기타 1: 포유류, 2: 조류
######
prediction = tf.argmax(model, 1)
target = tf.argmax(Y, 1)
print('예측값:', sess.run(prediction, feed_dict={X: x_data}))
print('실제값:', sess.run(target, feed_dict={Y: y_data}))

is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('정확도: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_data, Y: y_data}))

10 1.1051801
20 1.0020205
30 0.9381085
40 0.8582096
50 0.7657089
60 0.6626768
70 0.5538201
80 0.45262825
90 0.36397853
100 0.29273364
예측값: [0 1 2 0 0 2]
실제값: [0 1 2 0 0 2]
정확도: 100.00


## 학습 모델 저장하고 재사용하기

In [102]:
import tensorflow as tf
import numpy as np


data = np.loadtxt('C:\\Users\\EXEM\\Desktop/data.csv', delimiter=',', unpack=True, dtype='float32')

x_data = np.transpose(data[0:2])
y_data = np.transpose(data[2:])

`unpack=True, transpose` : 데이터의 행과 열을 뒤바꿔주는 옵션

In [103]:
global_step = tf.Variable(0, trainable=False, name='global_step')

In [104]:
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform([2,10],-1.,1.))
L1 = tf.nn.relu(tf.matmul(X,W1))

W2 = tf.Variable(tf.random_uniform([10,20],-1.,1.))
L2 = tf.nn.relu(tf.matmul(L1,W2))

W3 = tf.Variable(tf.random_uniform([20,3],-1.,1.))
model = tf.matmul(L2,W3)

cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y, logits=model))

optimizer = tf.train.AdadeltaOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost, global_step=global_step)

In [105]:
sess = tf.Session()
# 모델을 저장하는 코드
saver = tf.train.Saver(tf.global_variables())

In [106]:
ckpt = tf.train.get_checkpoint_state('C:\\Users\\EXEM\\model')
if ckpt and tf.train.checkpoint_exists(ckpt.model_checkpoint_path):
    saver.restore(sess, ckpt.model_checkpoint_path)
else:
    sess.run(tf.global_variables_initializer())

In [110]:
for step in range(2):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})
    
    print('Step: %d' % sess.run(global_step), 'Cost: %.3f' % sess.run(cost, feed_dict={X: x_data, Y: y_data}))

Step: 3 Cost: 1.801
Step: 4 Cost: 1.801


In [111]:
saver.save(sess, './model/dnn.ckpt', global_step=global_step)

'./model/dnn.ckpt-4'

In [112]:
prediction = tf.argmax(model,1)
target = tf.argmax(Y,1)
print('예측값:', sess.run(prediction, feed_dict={X: x_data}))
print('실제값:', sess.run(target, feed_dict={Y: y_data}))

is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('정확도: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_data, Y: y_data}))

예측값: [0 0 2 0 0 0]
실제값: [0 1 2 0 0 2]
정확도: 66.67


## 텐서보드 사용하기

In [180]:
import tensorflow as tf
import numpy as np


data = np.loadtxt('C:\\Users\\EXEM\\Desktop/data.csv', delimiter=',', unpack=True, dtype='float32')

x_data = np.transpose(data[0:2])
y_data = np.transpose(data[2:])

print(x_data,
      y_data)

[[0. 0.]
 [1. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [174]:
global_step = tf.Variable(0, trainable=False, name='global_step')

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [175]:
with tf.name_scope('layer1'):
    W1 = tf.Variable(tf.random_uniform([2,10],-1.,1.), name='W1')
    L1 = tf.nn.relu(tf.matmul(X,W1))

with tf.name_scope('layer2'):
    W2 = tf.Variable(tf.random_uniform([10,20],-1.,1.), name='W2')
    L2 = tf.nn.relu(tf.matmul(L1,W2))

with tf.name_scope('layer3'):
    W3 = tf.Variable(tf.random_uniform([20,3],-1.,1.), name='W3')
    model = tf.matmul(L2,W3)

with tf.name_scope('optimizer'):
    cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y, logits=model))

    optimizer = tf.train.AdadeltaOptimizer(learning_rate=0.01)
    train_op = optimizer.minimize(cost, global_step=global_step)
    
    tf.summary.scalar('cost', cost)

In [176]:
#########
# 신경망 모델 학습
######
sess = tf.Session()
saver = tf.train.Saver(tf.global_variables())

ckpt = tf.train.get_checkpoint_state('./model')
if ckpt and tf.train.checkpoint_exists(ckpt.model_checkpoint_path):
    saver.restore(sess, ckpt.model_checkpoint_path)
else:
    sess.run(tf.global_variables_initializer())

In [177]:
# 텐서보드에서 표시해주기 위한 텐서들을 수집합니다.
merged = tf.summary.merge_all()
# 저장할 그래프와 텐서값들을 저장할 디렉토리를 설정합니다.
writer = tf.summary.FileWriter('./logs', sess.graph)
# 이렇게 저장한 로그는, 학습 후 다음의 명령어를 이용해 웹서버를 실행시킨 뒤
# tensorboard --logdir=./logs
# 다음 주소와 웹브라우저를 이용해 텐서보드에서 확인할 수 있습니다.
# http://localhost:6006

In [182]:
# 최적화 진행
for step in range(100):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})

    print('Step: %d, ' % sess.run(global_step), 'Cost: %.3f' % sess.run(cost, feed_dict={X:x_data, Y:y_data}))

    # 적절한 시점에 저장할 값들을 수집하고 저장합니다.
    summary = sess.run(merged, feed_dict={X: x_data, Y: y_data})
    writer.add_summary(summary, global_step=sess.run(global_step))

saver.save(sess, './model/dnn.ckpt', global_step=global_step)

Step: 2,  Cost: 1.259


InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_14' with dtype float
	 [[Node: Placeholder_14 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder_14', defined at:
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelapp.py", line 478, in start
    self.io_loop.start()
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-88-0cc55e706a40>", line 13, in <module>
    Y = tf.placeholder(tf.float32)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1680, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 4105, in _placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3160, in create_op
    op_def=op_def)
  File "C:\Users\EXEM\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder_14' with dtype float
	 [[Node: Placeholder_14 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [172]:
#########
# 결과 확인
# 0: 기타 1: 포유류, 2: 조류
######
prediction = tf.argmax(model, 1)
target = tf.argmax(Y, 1)
print('예측값:', sess.run(prediction, feed_dict={X: x_data}))
print('실제값:', sess.run(target, feed_dict={Y: y_data}))

is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('정확도: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_data, Y: y_data}))

예측값: [0 1 2 0 0 2]
실제값: [0 1 2 0 0 2]
정확도: 100.00
